export const S3_REGION_TO_ENDPOINT = {
  'us-east-2':      's3.us-east-2.amazonaws.com',
  'us-east-1':      's3.us-east-1.amazonaws.com',
  'us-west-1':      's3.us-west-1.amazonaws.com',
  'us-west-2':      's3.us-west-2.amazonaws.com',
  'af-south-1':     's3.af-south-1.amazonaws.com',
  'ap-east-1':      's3.ap-east-1.amazonaws.com',
  'ap-south-1':     's3.ap-south-1.amazonaws.com',
  'ap-northeast-3': 's3.ap-northeast-3.amazonaws.com',
  'ap-northeast-2': 's3.ap-northeast-2.amazonaws.com',
  'ap-southeast-1': 's3.ap-southeast-1.amazonaws.com',
  'ap-southeast-2': 's3.ap-southeast-2.amazonaws.com',
  'ap-northeast-1': 's3.ap-northeast-1.amazonaws.com',
  'ca-central-1':   's3.ca-central-1.amazonaws.com',
  'cn-northwest-1': 's3.cn-northwest-1.amazonaws.com.cn',
  'eu-central-1':   's3.eu-central-1.amazonaws.com',
  'eu-west-1':      's3.eu-west-1.amazonaws.com',
  'eu-west-2':      's3.eu-west-2.amazonaws.com',
  'eu-south-1':     's3.eu-south-1.amazonaws.com',
  'eu-west-3':      's3.eu-west-3.amazonaws.com',
  'eu-north-1':     's3.eu-north-1.amazonaws.com',
  'ap-southeast-3': 's3.ap-southeast-3.amazonaws.com',
  'me-south-1':     's3.me-south-1.amazonaws.com',
  'me-central-1':   's3.me-central-1.amazonaws.com',
  'sa-east-1':      's3.sa-east-1.amazonaws.com',
  'us-gov-east-1':  's3.us-gov-east-1.amazonaws.com',
  'us-gov-west-1':  's3.us-gov-west-1.amazonaws.com',
};
export const S3_ENDPOINT_TO_REGION = Object.entries(S3_REGION_TO_ENDPOINT).reduce((agg, [region, endpoint]) => ({ ...agg, [endpoint]: region }));
export const S3_REGIONS = Object.keys(S3_REGION_TO_ENDPOINT);
export const S3_ENDPOINTS = Object.values(S3_REGION_TO_ENDPOINT);
