// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - ragu               v1.0.0
// source: github.com/rancher/opni/plugins/logging/pkg/apis/opensearch/opensearch.proto

package opensearch

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OpensearchClient is the client API for Opensearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpensearchClient interface {
	GetDetails(ctx context.Context, in *ClusterReference, opts ...grpc.CallOption) (*OpensearchDetails, error)
}

type opensearchClient struct {
	cc grpc.ClientConnInterface
}

func NewOpensearchClient(cc grpc.ClientConnInterface) OpensearchClient {
	return &opensearchClient{cc}
}

func (c *opensearchClient) GetDetails(ctx context.Context, in *ClusterReference, opts ...grpc.CallOption) (*OpensearchDetails, error) {
	out := new(OpensearchDetails)
	err := c.cc.Invoke(ctx, "/opensearch.Opensearch/GetDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpensearchServer is the server API for Opensearch service.
// All implementations must embed UnimplementedOpensearchServer
// for forward compatibility
type OpensearchServer interface {
	GetDetails(context.Context, *ClusterReference) (*OpensearchDetails, error)
	mustEmbedUnimplementedOpensearchServer()
}

// UnimplementedOpensearchServer must be embedded to have forward compatible implementations.
type UnimplementedOpensearchServer struct {
}

func (UnimplementedOpensearchServer) GetDetails(context.Context, *ClusterReference) (*OpensearchDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetails not implemented")
}
func (UnimplementedOpensearchServer) mustEmbedUnimplementedOpensearchServer() {}

// UnsafeOpensearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpensearchServer will
// result in compilation errors.
type UnsafeOpensearchServer interface {
	mustEmbedUnimplementedOpensearchServer()
}

func RegisterOpensearchServer(s grpc.ServiceRegistrar, srv OpensearchServer) {
	s.RegisterService(&Opensearch_ServiceDesc, srv)
}

func _Opensearch_GetDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterReference)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpensearchServer).GetDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opensearch.Opensearch/GetDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpensearchServer).GetDetails(ctx, req.(*ClusterReference))
	}
	return interceptor(ctx, in, info, handler)
}

// Opensearch_ServiceDesc is the grpc.ServiceDesc for Opensearch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Opensearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opensearch.Opensearch",
	HandlerType: (*OpensearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDetails",
			Handler:    _Opensearch_GetDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/rancher/opni/plugins/logging/pkg/apis/opensearch/opensearch.proto",
}
