apiVersion: apps/v1
kind: Deployment
metadata:
  name: nulog-inference-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nulog-inference-service
  template:
    metadata:
      labels:
        app: nulog-inference-service
    spec:
      containers:
      - name: nulog-inference-service
        image: tybalex/nulog-inference-service
        imagePullPolicy: Always
        env:
        - name: NATS_SERVER_URL
          value: "nats://nats_client:VfU6TcAl9x@nats-client.default.svc:4222"
        - name: ES_ENDPOINT
          value: "http://elasticsearch-coordinating-only.default.svc.cluster.local:9200"
        - name: MINIO_ACCESS_KEY
          value: "myaccesskey"
        - name: MINIO_SECRET_KEY
          value: "mysecretkey"
        resources:
          limits:
            nvidia.com/gpu: 1
