# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- logging/logging.opni.io_clusterflows.yaml
- logging/logging.opni.io_clusteroutputs.yaml
- logging/logging.opni.io_flows.yaml
- logging/logging.opni.io_loggings.yaml
- logging/logging.opni.io_outputs.yaml
- logging/logging.opni.io_syslogngclusterflows.yaml
- logging/logging.opni.io_syslogngclusteroutputs.yaml
- logging/logging.opni.io_syslogngoutputs.yaml
- logging/logging.opni.io_syslogngflows.yaml
- bases/logging.opni.io_logadapters.yaml
- bases/logging.opni.io_collectorconfigs.yaml
- bases/logging.opni.io_datapreppers.yaml
- bases/core.opni.io_bootstraptokens.yaml
- bases/core.opni.io_keyrings.yaml
- bases/core.opni.io_collectors.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
