# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- logging/logging.opni.io_clusterflows.yaml
- logging/logging.opni.io_clusteroutputs.yaml
- logging/logging.opni.io_flows.yaml
- logging/logging.opni.io_loggings.yaml
- logging/logging.opni.io_outputs.yaml
- bases/opni.io_logadapters.yaml
- bases/opni.io_datapreppers.yaml
- bases/opni.io_bootstraptokens.yaml
- bases/opni.io_keyrings.yaml
- bases/logging.opni.io_logadapters.yaml
- bases/logging.opni.io_datapreppers.yaml
- bases/monitoring.opni.io_bootstraptokens.yaml
- bases/monitoring.opni.io_keyrings.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_logadapters.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_logadapters.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
