---
kind: pipeline
type: docker
name: build-amd64
platform:
  os: linux
  arch: amd64
steps:
  - name: build-and-package
    image: docker
    environment: &dagger_env
      DAGGER_LOG_FORMAT: "plain"
      # DAGGER_CACHE_FROM: type=registry,mode=max,ref=rancher/opni-buildkit-cache
      # DAGGER_CACHE_TO: type=registry,mode=max,ref=rancher/opni-buildkit-cache
    commands:
      - apk add --no-cache curl
      - curl -sL https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.2.21 sh
      - bin/dagger version
      - bin/dagger do build
    volumes: &volumes
      - name: docker
        path: /var/run/docker.sock
      - name: docker-config
        path: /root/.docker
  - name: test
    image: docker
    environment:
      <<: *dagger_env
    commands:
      - bin/dagger do test
    volumes: *volumes
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
      files:
        - cover.out
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      branch:
        - main
        - release
  - name: publish-dockerhub-tag
    image: docker
    environment:
      <<: *dagger_env
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      TAG: ${DRONE_TAG}
    commands:
      - bin/dagger do push
    volumes: *volumes
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io
      refs:
        - refs/heads/main
        - refs/heads/release
        - refs/tags/*
  - name: publish-dockerhub-latest
    image: docker
    environment:
      <<: *dagger_env
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      TAG: latest
    commands:
      - bin/dagger do push
    volumes: *volumes
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io
      refs:
        - refs/heads/main
        - refs/heads/release
        - refs/tags/*
  - name: publish-dockerhub-main
    image: docker
    environment:
      <<: *dagger_env
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      TAG: main
    commands:
      - bin/dagger do push
    volumes: *volumes
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      branch:
        - main
        - release
  - name: publish-opensearch-dashboards-latest
    image: docker
    environment:
      <<: *dagger_env
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - bin/dagger do dashboards
    volumes: *volumes
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      branch:
        - main
        - release
  - name: publish-opensearch-latest
    image: docker
    environment:
      <<: *dagger_env
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - bin/dagger do opensearch
    volumes: *volumes
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      branch:
        - main
        - release
  - name: publish-opensearch-dashboards-tag
    image: docker
    environment:
      <<: *dagger_env
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - bin/dagger do dashboards
    volumes: *volumes
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io
      refs:
        - refs/heads/main
        - refs/tags/*
  - name: publish-opensearch-tag
    image: docker
    environment:
      <<: *dagger_env
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - bin/dagger do opensearch
    volumes: *volumes
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io
      refs:
        - refs/heads/main
        - refs/heads/release
        - refs/tags/*
  - name: e2e-nightly
    image: docker
    environment:
      <<: *dagger_env
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      PULUMI_ACCESS_TOKEN:
        from_secret: pulumi_access_token
    commands:
      - bin/dagger do e2e
    volumes: *volumes
    when:
      event:
        - cron
      instance:
        - drone-publish.rancher.io
      cron:
        - e2e-nightly
  - name: publish-aiops
    image: docker
    environment:
      <<: *dagger_env
      TWINE_PASSWORD:
        from_secret: twine_password
    commands:
      - bin/dagger do aiops
    volumes: *volumes
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io
      refs:
        - refs/heads/main
        - refs/heads/release
        - refs/tags/*
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: docker-config
    host:
      path: /root/.docker
