run:
  tests: true
  timeout: 5m
  skip-dirs:
    - pkg/test/mock
    - pkg/test/testdata
  skip-files:
    - magefile.go
    - /zz_generated
linters:
  disable-all: true
  enable:
    - revive
    - ineffassign
    - gofmt
linters-settings:
  revive:
    ignore-generated-header: false
    severity: warning
    rules:
      - name: atomic
      - name: context-as-argument
      - name: context-keys-type
      - name: empty-block
      - name: errorf
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: imports-blacklist
        arguments:
          ["grpc.go4.org/**", "github.com/gogo/status", "github.com/gogo/codes"]
      - name: increment-decrement
      # - name: indent-error-flow
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: time-naming
      - name: unexported-return
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: useless-break
      - name: var-declaration
      - name: waitgroup-by-value
