
url: local
version: 0.6.0-dev1
workingDir: charts
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
    addCRDValidationToMainChart: true