{{- $namespace := printf "%s" (include "opni-agent.namespace" .) }}
{{- if or .Values.logging.enabled .Values.agent.version "v2" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: opni-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opni-serving-cert
  namespace: {{ $namespace }}
spec:
  dnsNames:
    - "opni-webhook.{{ $namespace }}.svc"
    - "opni-webhook.{{ $namespace }}.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: opni-selfsigned-issuer
  secretName: webhook-server-cert
{{- end }}