{{- $namespace := printf "%s" (include "opni.namespace" .) }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ $namespace }}/opni-serving-cert
  name: opni-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
    - v1
    - v1beta1
    clientConfig:
      service:
        name: opni-webhook
        namespace: {{ $namespace }}
        path: /mutate-logging-opni-io-v1beta1-logadapter
    failurePolicy: Fail
    name: mlogadapter.kb.io
    rules:
    - apiGroups:
      - logging.opni.io
      apiVersions:
      - v1beta1
      operations:
      - CREATE
      - UPDATE
      resources:
      - logadapters
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: opni-webhook
        namespace: {{ $namespace }}
        path: /mutate-opni-io-v1beta2-logadapter
    failurePolicy: Fail
    name: mlogadapter2.kb.io
    rules:
      - apiGroups:
          - opni.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - logadapters
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ $namespace }}/opni-serving-cert
  name: opni-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
    - v1
    - v1beta1
    clientConfig:
      service:
        name: opni-webhook
        namespace: {{ $namespace }}
        path: /validate-logging-opni-io-v1beta1-logadapter
    failurePolicy: Fail
    name: vlogadapter.kb.io
    rules:
    - apiGroups:
      - logging.opni.io
      apiVersions:
      - v1beta1
      operations:
      - CREATE
      - UPDATE
      resources:
      - logadapters
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: opni-webhook
        namespace: {{ $namespace }}
        path: /validate-opni-io-v1beta2-logadapter
    failurePolicy: Fail
    name: vlogadapter2.kb.io
    rules:
      - apiGroups:
          - opni.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - logadapters
    sideEffects: None