apiVersion: apps/v1
kind: Deployment
metadata:
  name: drain-service
  namespace: opni-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drain-service
  template:
    metadata:
      labels:
        app: drain-service
    spec:
      containers:
      - name: drain-service
        image: rancher/opni-drain-service:v0.1.1
        imagePullPolicy: Always
        env:
        - name: NATS_SERVER_URL
          value: "nats://nats_client:%NATS_PASSWORD%@nats-client.opni-system.svc:4222"
        - name: MINIO_SERVER_URL
          value: "http://minio.opni-system.svc.cluster.local:9000"
        - name: MINIO_ACCESS_KEY
          value: "%MINIO_ACCESS_KEY%"
        - name: MINIO_SECRET_KEY
          value: "%MINIO_SECRET_KEY%"
        - name: ES_ENDPOINT
          value: "https://opendistro-es-client-service.opni-system.svc.cluster.local:9200"
        - name: FAIL_KEYWORDS
          value: "fail,error,missing,unable"
        - name: MINIO_SERVER_URL
          value: "http://minio.opni-system.svc.cluster.local:9000"
        - name: MINIO_ACCESS_KEY
          value: "%MINIO_ACCESS_KEY%"
        - name: MINIO_SECRET_KEY
          value: "%MINIO_SECRET_KEY%"
        - name: ES_USERNAME
          value: "%ES_USER%"
        - name: ES_PASSWORD
          value: "%ES_PASSWORD%"