apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: "opendistro-es"
  namespace: opni-system
spec:
  chartContent: %OPENDISTRO_ES_CHART_CONTENT%
  set:
    elasticsearch.master.persistence.enabled: "true"
    elasticsearch.master.persistence.storageClass: "local-path"
    elasticsearch.data.persistence.enabled: "true"
    elasticsearch.data.persistence.storageClass: "local-path"
    elasticsearch.username: "%ES_USER%"
    elasticsearch.password: "%ES_PASSWORD%"