apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - bases/
patchesStrategicMerge:
  - patches/versions.yaml # If needed, edit this file to change versions

  # Uncomment one of the following to deploy a LogAdapter
  # (or leave all examples commented to use the "generic" LogAdapter)
  # - examples/logAdapters/logAdapter_k3s_openrc.yaml
  # - examples/logAdapters/logAdapter_k3s_systemd.yaml
  # - examples/logAdapters/logAdapter_rke.yaml
  # - examples/logAdapters/logAdapter_rke2.yaml

  # Uncomment to enable GPU support
  # - patches/gpu.yaml

  # Uncomment to enable persistent storage
  # - patches/persistence.yaml # edit this file to set storage size

  # Uncomment to enable metric anomaly detection (experimental)
  # - patches/metrics.yaml # edit this file to set your prometheus endpoint

  # Uncomment to enable external S3 storage
  # - examples/s3/external_s3.yaml # edit this file to configure your S3 server

  # Uncomment to enable Insights Service
  # - patches/insights.yaml # edit this file to configure your Insights server

resources:
  # Uncomment to enable GPU support
  # - examples/nfd/aio.yaml
  
  # Uncomment one of the following depending on your GPU type
  # - examples/gpu/gpu.yaml
  # - examples/gpu/vgpu.yaml # a template for this file is provided in examples/gpu
