apiVersion: opni.io/v1beta1
kind: LogAdapter
metadata:
  name: logadapter-sample
spec:
  provider: K3S
  opniCluster:
    name: opnicluster-sample
    namespace: default
  k3s:
    containerEngine: openrc
