{
 "title": "SockShop-Live-Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Main Panel",
   "type": "graph",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "normal",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "anomaly_predicted_count:0",
     "timeField": "time"
    },
    {
     "alias": "suspicious",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "anomaly_predicted_count:1",
     "timeField": "time"
    },
    {
     "alias": "anomaly",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "anomaly_predicted_count:2",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Log Panel",
   "type": "logs",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Anomaly Panel",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "anomaly",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "anomaly_predicted_count:2",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Alert Panel",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}