// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v1.0.0
// source: github.cim/rancher/opni/plugins/metrics/pkg/apis/remoteread/remoteread.proto

package remoteread

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TargetStatus_State int32

const (
	TargetStatus_NotRunning TargetStatus_State = 0
	TargetStatus_Running    TargetStatus_State = 1
	TargetStatus_Failed     TargetStatus_State = 2
	TargetStatus_Complete   TargetStatus_State = 3
	TargetStatus_Stopped    TargetStatus_State = 4
)

// Enum value maps for TargetStatus_State.
var (
	TargetStatus_State_name = map[int32]string{
		0: "NotRunning",
		1: "Running",
		2: "Failed",
		3: "Complete",
		4: "Stopped",
	}
	TargetStatus_State_value = map[string]int32{
		"NotRunning": 0,
		"Running":    1,
		"Failed":     2,
		"Complete":   3,
		"Stopped":    4,
	}
)

func (x TargetStatus_State) Enum() *TargetStatus_State {
	p := new(TargetStatus_State)
	*p = x
	return p
}

func (x TargetStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_enumTypes[0].Descriptor()
}

func (TargetStatus_State) Type() protoreflect.EnumType {
	return &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_enumTypes[0]
}

func (x TargetStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetStatus_State.Descriptor instead.
func (TargetStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{2, 0}
}

type LabelMatcher_Type int32

const (
	LabelMatcher_Equal         LabelMatcher_Type = 0
	LabelMatcher_NotEqual      LabelMatcher_Type = 1
	LabelMatcher_RegexEqual    LabelMatcher_Type = 2
	LabelMatcher_NotRegexEqual LabelMatcher_Type = 3
)

// Enum value maps for LabelMatcher_Type.
var (
	LabelMatcher_Type_name = map[int32]string{
		0: "Equal",
		1: "NotEqual",
		2: "RegexEqual",
		3: "NotRegexEqual",
	}
	LabelMatcher_Type_value = map[string]int32{
		"Equal":         0,
		"NotEqual":      1,
		"RegexEqual":    2,
		"NotRegexEqual": 3,
	}
)

func (x LabelMatcher_Type) Enum() *LabelMatcher_Type {
	p := new(LabelMatcher_Type)
	*p = x
	return p
}

func (x LabelMatcher_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LabelMatcher_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_enumTypes[1].Descriptor()
}

func (LabelMatcher_Type) Type() protoreflect.EnumType {
	return &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_enumTypes[1]
}

func (x LabelMatcher_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LabelMatcher_Type.Descriptor instead.
func (LabelMatcher_Type) EnumDescriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{16, 0}
}

type Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta   *TargetMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Spec   *TargetSpec   `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status *TargetStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Target) Reset() {
	*x = Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{0}
}

func (x *Target) GetMeta() *TargetMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Target) GetSpec() *TargetSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Target) GetStatus() *TargetStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type TargetMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ClusterId string `protobuf:"bytes,2,opt,name=clusterId,proto3" json:"clusterId,omitempty"`
}

func (x *TargetMeta) Reset() {
	*x = TargetMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetMeta) ProtoMessage() {}

func (x *TargetMeta) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetMeta.ProtoReflect.Descriptor instead.
func (*TargetMeta) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{1}
}

func (x *TargetMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TargetMeta) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type TargetStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// this is the progress of the last known import
	Progress *TargetProgress    `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	Message  string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	State    TargetStatus_State `protobuf:"varint,3,opt,name=state,proto3,enum=remoteread.TargetStatus_State" json:"state,omitempty"`
}

func (x *TargetStatus) Reset() {
	*x = TargetStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetStatus) ProtoMessage() {}

func (x *TargetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetStatus.ProtoReflect.Descriptor instead.
func (*TargetStatus) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{2}
}

func (x *TargetStatus) GetProgress() *TargetProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *TargetStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TargetStatus) GetState() TargetStatus_State {
	if x != nil {
		return x.State
	}
	return TargetStatus_NotRunning
}

type TargetSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
}

func (x *TargetSpec) Reset() {
	*x = TargetSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetSpec) ProtoMessage() {}

func (x *TargetSpec) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetSpec.ProtoReflect.Descriptor instead.
func (*TargetSpec) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{3}
}

func (x *TargetSpec) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type TargetDiff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TargetDiff) Reset() {
	*x = TargetDiff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetDiff) ProtoMessage() {}

func (x *TargetDiff) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetDiff.ProtoReflect.Descriptor instead.
func (*TargetDiff) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{4}
}

func (x *TargetDiff) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *TargetDiff) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TargetList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Targets []*Target `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
}

func (x *TargetList) Reset() {
	*x = TargetList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetList) ProtoMessage() {}

func (x *TargetList) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetList.ProtoReflect.Descriptor instead.
func (*TargetList) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{5}
}

func (x *TargetList) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

type TargetProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTimestamp    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=startTimestamp,proto3" json:"startTimestamp,omitempty"`
	LastReadTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=lastReadTimestamp,proto3" json:"lastReadTimestamp,omitempty"`
	EndTimestamp      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=endTimestamp,proto3" json:"endTimestamp,omitempty"`
}

func (x *TargetProgress) Reset() {
	*x = TargetProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetProgress) ProtoMessage() {}

func (x *TargetProgress) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetProgress.ProtoReflect.Descriptor instead.
func (*TargetProgress) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{6}
}

func (x *TargetProgress) GetStartTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTimestamp
	}
	return nil
}

func (x *TargetProgress) GetLastReadTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReadTimestamp
	}
	return nil
}

func (x *TargetProgress) GetEndTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTimestamp
	}
	return nil
}

type TargetAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target    *Target `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	ClusterId string  `protobuf:"bytes,2,opt,name=clusterId,proto3" json:"clusterId,omitempty"`
}

func (x *TargetAddRequest) Reset() {
	*x = TargetAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetAddRequest) ProtoMessage() {}

func (x *TargetAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetAddRequest.ProtoReflect.Descriptor instead.
func (*TargetAddRequest) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{7}
}

func (x *TargetAddRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *TargetAddRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type TargetEditRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta       *TargetMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	TargetDiff *TargetDiff `protobuf:"bytes,2,opt,name=targetDiff,proto3" json:"targetDiff,omitempty"`
}

func (x *TargetEditRequest) Reset() {
	*x = TargetEditRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetEditRequest) ProtoMessage() {}

func (x *TargetEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetEditRequest.ProtoReflect.Descriptor instead.
func (*TargetEditRequest) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{8}
}

func (x *TargetEditRequest) GetMeta() *TargetMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TargetEditRequest) GetTargetDiff() *TargetDiff {
	if x != nil {
		return x.TargetDiff
	}
	return nil
}

type TargetRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *TargetMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *TargetRemoveRequest) Reset() {
	*x = TargetRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRemoveRequest) ProtoMessage() {}

func (x *TargetRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRemoveRequest.ProtoReflect.Descriptor instead.
func (*TargetRemoveRequest) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{9}
}

func (x *TargetRemoveRequest) GetMeta() *TargetMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type TargetListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterId string `protobuf:"bytes,1,opt,name=clusterId,proto3" json:"clusterId,omitempty"`
}

func (x *TargetListRequest) Reset() {
	*x = TargetListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetListRequest) ProtoMessage() {}

func (x *TargetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetListRequest.ProtoReflect.Descriptor instead.
func (*TargetListRequest) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{10}
}

func (x *TargetListRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type StartReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target *Target `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Query  *Query  `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// allow for forcing a remote read when Query.startTimestamp > Target.meta.lastReadTimestamp
	ForceOverlap bool `protobuf:"varint,3,opt,name=forceOverlap,proto3" json:"forceOverlap,omitempty"`
}

func (x *StartReadRequest) Reset() {
	*x = StartReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReadRequest) ProtoMessage() {}

func (x *StartReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReadRequest.ProtoReflect.Descriptor instead.
func (*StartReadRequest) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{11}
}

func (x *StartReadRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *StartReadRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *StartReadRequest) GetForceOverlap() bool {
	if x != nil {
		return x.ForceOverlap
	}
	return false
}

type StopReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *TargetMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *StopReadRequest) Reset() {
	*x = StopReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopReadRequest) ProtoMessage() {}

func (x *StopReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopReadRequest.ProtoReflect.Descriptor instead.
func (*StopReadRequest) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{12}
}

func (x *StopReadRequest) GetMeta() *TargetMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type TargetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *TargetMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *TargetStatusRequest) Reset() {
	*x = TargetStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetStatusRequest) ProtoMessage() {}

func (x *TargetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetStatusRequest.ProtoReflect.Descriptor instead.
func (*TargetStatusRequest) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{13}
}

func (x *TargetStatusRequest) GetMeta() *TargetMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type TargetStatusUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta      *TargetMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	NewStatus *TargetStatus `protobuf:"bytes,2,opt,name=newStatus,proto3" json:"newStatus,omitempty"`
}

func (x *TargetStatusUpdateRequest) Reset() {
	*x = TargetStatusUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetStatusUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetStatusUpdateRequest) ProtoMessage() {}

func (x *TargetStatusUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetStatusUpdateRequest.ProtoReflect.Descriptor instead.
func (*TargetStatusUpdateRequest) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{14}
}

func (x *TargetStatusUpdateRequest) GetMeta() *TargetMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TargetStatusUpdateRequest) GetNewStatus() *TargetStatus {
	if x != nil {
		return x.NewStatus
	}
	return nil
}

// PromQL query
type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=startTimestamp,proto3" json:"startTimestamp,omitempty"`
	EndTimestamp   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=endTimestamp,proto3" json:"endTimestamp,omitempty"`
	Matchers       []*LabelMatcher        `protobuf:"bytes,3,rep,name=matchers,proto3" json:"matchers,omitempty"`
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{15}
}

func (x *Query) GetStartTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTimestamp
	}
	return nil
}

func (x *Query) GetEndTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTimestamp
	}
	return nil
}

func (x *Query) GetMatchers() []*LabelMatcher {
	if x != nil {
		return x.Matchers
	}
	return nil
}

type LabelMatcher struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  LabelMatcher_Type `protobuf:"varint,1,opt,name=type,proto3,enum=remoteread.LabelMatcher_Type" json:"type,omitempty"`
	Name  string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value string            `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LabelMatcher) Reset() {
	*x = LabelMatcher{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LabelMatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelMatcher) ProtoMessage() {}

func (x *LabelMatcher) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelMatcher.ProtoReflect.Descriptor instead.
func (*LabelMatcher) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{16}
}

func (x *LabelMatcher) GetType() LabelMatcher_Type {
	if x != nil {
		return x.Type
	}
	return LabelMatcher_Equal
}

func (x *LabelMatcher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabelMatcher) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Progress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=startTimestamp,proto3" json:"startTimestamp,omitempty"`
	EndTimestamp   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=endTimestamp,proto3" json:"endTimestamp,omitempty"`
	PercentDone    float32                `protobuf:"fixed32,3,opt,name=percentDone,proto3" json:"percentDone,omitempty"`
}

func (x *Progress) Reset() {
	*x = Progress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP(), []int{17}
}

func (x *Progress) GetStartTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTimestamp
	}
	return nil
}

func (x *Progress) GetEndTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTimestamp
	}
	return nil
}

func (x *Progress) GetPercentDone() float32 {
	if x != nil {
		return x.PercentDone
	}
	return 0
}

var File_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto protoreflect.FileDescriptor

var file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDesc = []byte{
	0x0a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x69, 0x6d, 0x2f, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x6e, 0x69, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x73, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70,
	0x69, 0x73, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2f, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x01,
	0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72,
	0x65, 0x61, 0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63,
	0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x3e, 0x0a, 0x0a, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x22, 0xe3, 0x01, 0x0a, 0x0c, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x36, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65,
	0x61, 0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61,
	0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x4b, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x6f, 0x74, 0x52, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0c, 0x0a,
	0x08, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x10, 0x04, 0x22, 0x28, 0x0a, 0x0a, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x22, 0x3c, 0x0a, 0x0a, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x44, 0x69, 0x66, 0x66,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x3a, 0x0a, 0x0a, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2c,
	0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x22, 0xde, 0x01, 0x0a,
	0x0e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x42, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x48, 0x0a, 0x11, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x61, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x11, 0x6c, 0x61, 0x73, 0x74,
	0x52, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x3e, 0x0a,
	0x0c, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0c, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x5c, 0x0a,
	0x10, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2a, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x77, 0x0a, 0x11, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2a, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x0a,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x44, 0x69, 0x66, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x44, 0x69, 0x66, 0x66, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x44, 0x69, 0x66, 0x66, 0x22, 0x41, 0x0a, 0x13, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x6d,
	0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x65, 0x74,
	0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x11, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x10, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2a, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x4f, 0x76, 0x65,
	0x72, 0x6c, 0x61, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x66, 0x6f, 0x72, 0x63,
	0x65, 0x4f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x70, 0x22, 0x3d, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x70,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x6d,
	0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x65, 0x74,
	0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x41, 0x0a, 0x13, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a,
	0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x7f, 0x0a, 0x19, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65,
	0x61, 0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d,
	0x65, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72,
	0x65, 0x61, 0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x09, 0x6e, 0x65, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xc1, 0x01, 0x0a, 0x05,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x42, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x3e, 0x0a, 0x0c, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x34, 0x0a, 0x08, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x72, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x73, 0x22,
	0xaf, 0x01, 0x0a, 0x0c, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72,
	0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d,
	0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x42, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x0e,
	0x0a, 0x0a, 0x52, 0x65, 0x67, 0x65, 0x78, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x10, 0x02, 0x12, 0x11,
	0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x67, 0x65, 0x78, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x10,
	0x03, 0x22, 0xb0, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x42,
	0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x3e, 0x0a, 0x0c, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x44, 0x6f, 0x6e,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x44, 0x6f, 0x6e, 0x65, 0x32, 0xc9, 0x04, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52,
	0x65, 0x61, 0x64, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x41, 0x0a, 0x09, 0x41, 0x64,
	0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x72, 0x65, 0x61, 0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x43, 0x0a,
	0x0a, 0x45, 0x64, 0x69, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x1d, 0x2e, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x45,
	0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x47, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x12, 0x1f, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x44, 0x0a, 0x0b, 0x4c,
	0x69, 0x73, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x4c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61,
	0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65,
	0x61, 0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x3d, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1c, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3b,
	0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x1b, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72,
	0x65, 0x61, 0x64, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x53, 0x0a, 0x12, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x25, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x32, 0xe2, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1c, 0x2e,
	0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x3b, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x1b, 0x2e, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x53, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x72,
	0x65, 0x61, 0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x69, 0x6d, 0x2f, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x6e, 0x69,
	0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x72, 0x65, 0x61, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescOnce sync.Once
	file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescData = file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDesc
)

func file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescGZIP() []byte {
	file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescOnce.Do(func() {
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescData)
	})
	return file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDescData
}

var file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_goTypes = []interface{}{
	(TargetStatus_State)(0),           // 0: remoteread.TargetStatus.State
	(LabelMatcher_Type)(0),            // 1: remoteread.LabelMatcher.Type
	(*Target)(nil),                    // 2: remoteread.Target
	(*TargetMeta)(nil),                // 3: remoteread.TargetMeta
	(*TargetStatus)(nil),              // 4: remoteread.TargetStatus
	(*TargetSpec)(nil),                // 5: remoteread.TargetSpec
	(*TargetDiff)(nil),                // 6: remoteread.TargetDiff
	(*TargetList)(nil),                // 7: remoteread.TargetList
	(*TargetProgress)(nil),            // 8: remoteread.TargetProgress
	(*TargetAddRequest)(nil),          // 9: remoteread.TargetAddRequest
	(*TargetEditRequest)(nil),         // 10: remoteread.TargetEditRequest
	(*TargetRemoveRequest)(nil),       // 11: remoteread.TargetRemoveRequest
	(*TargetListRequest)(nil),         // 12: remoteread.TargetListRequest
	(*StartReadRequest)(nil),          // 13: remoteread.StartReadRequest
	(*StopReadRequest)(nil),           // 14: remoteread.StopReadRequest
	(*TargetStatusRequest)(nil),       // 15: remoteread.TargetStatusRequest
	(*TargetStatusUpdateRequest)(nil), // 16: remoteread.TargetStatusUpdateRequest
	(*Query)(nil),                     // 17: remoteread.Query
	(*LabelMatcher)(nil),              // 18: remoteread.LabelMatcher
	(*Progress)(nil),                  // 19: remoteread.Progress
	(*timestamppb.Timestamp)(nil),     // 20: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 21: google.protobuf.Empty
}
var file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_depIdxs = []int32{
	3,  // 0: remoteread.Target.meta:type_name -> remoteread.TargetMeta
	5,  // 1: remoteread.Target.spec:type_name -> remoteread.TargetSpec
	4,  // 2: remoteread.Target.status:type_name -> remoteread.TargetStatus
	8,  // 3: remoteread.TargetStatus.progress:type_name -> remoteread.TargetProgress
	0,  // 4: remoteread.TargetStatus.state:type_name -> remoteread.TargetStatus.State
	2,  // 5: remoteread.TargetList.targets:type_name -> remoteread.Target
	20, // 6: remoteread.TargetProgress.startTimestamp:type_name -> google.protobuf.Timestamp
	20, // 7: remoteread.TargetProgress.lastReadTimestamp:type_name -> google.protobuf.Timestamp
	20, // 8: remoteread.TargetProgress.endTimestamp:type_name -> google.protobuf.Timestamp
	2,  // 9: remoteread.TargetAddRequest.target:type_name -> remoteread.Target
	3,  // 10: remoteread.TargetEditRequest.meta:type_name -> remoteread.TargetMeta
	6,  // 11: remoteread.TargetEditRequest.targetDiff:type_name -> remoteread.TargetDiff
	3,  // 12: remoteread.TargetRemoveRequest.meta:type_name -> remoteread.TargetMeta
	2,  // 13: remoteread.StartReadRequest.target:type_name -> remoteread.Target
	17, // 14: remoteread.StartReadRequest.query:type_name -> remoteread.Query
	3,  // 15: remoteread.StopReadRequest.meta:type_name -> remoteread.TargetMeta
	3,  // 16: remoteread.TargetStatusRequest.meta:type_name -> remoteread.TargetMeta
	3,  // 17: remoteread.TargetStatusUpdateRequest.meta:type_name -> remoteread.TargetMeta
	4,  // 18: remoteread.TargetStatusUpdateRequest.newStatus:type_name -> remoteread.TargetStatus
	20, // 19: remoteread.Query.startTimestamp:type_name -> google.protobuf.Timestamp
	20, // 20: remoteread.Query.endTimestamp:type_name -> google.protobuf.Timestamp
	18, // 21: remoteread.Query.matchers:type_name -> remoteread.LabelMatcher
	1,  // 22: remoteread.LabelMatcher.type:type_name -> remoteread.LabelMatcher.Type
	20, // 23: remoteread.Progress.startTimestamp:type_name -> google.protobuf.Timestamp
	20, // 24: remoteread.Progress.endTimestamp:type_name -> google.protobuf.Timestamp
	9,  // 25: remoteread.RemoteReadGateway.AddTarget:input_type -> remoteread.TargetAddRequest
	10, // 26: remoteread.RemoteReadGateway.EditTarget:input_type -> remoteread.TargetEditRequest
	11, // 27: remoteread.RemoteReadGateway.RemoveTarget:input_type -> remoteread.TargetRemoveRequest
	12, // 28: remoteread.RemoteReadGateway.ListTargets:input_type -> remoteread.TargetListRequest
	15, // 29: remoteread.RemoteReadGateway.GetTargetStatus:input_type -> remoteread.TargetStatusRequest
	13, // 30: remoteread.RemoteReadGateway.Start:input_type -> remoteread.StartReadRequest
	14, // 31: remoteread.RemoteReadGateway.Stop:input_type -> remoteread.StopReadRequest
	16, // 32: remoteread.RemoteReadGateway.UpdateTargetStatus:input_type -> remoteread.TargetStatusUpdateRequest
	13, // 33: remoteread.RemoteReadAgent.Start:input_type -> remoteread.StartReadRequest
	14, // 34: remoteread.RemoteReadAgent.Stop:input_type -> remoteread.StopReadRequest
	16, // 35: remoteread.RemoteReadAgent.UpdateTargetStatus:input_type -> remoteread.TargetStatusUpdateRequest
	21, // 36: remoteread.RemoteReadGateway.AddTarget:output_type -> google.protobuf.Empty
	21, // 37: remoteread.RemoteReadGateway.EditTarget:output_type -> google.protobuf.Empty
	21, // 38: remoteread.RemoteReadGateway.RemoveTarget:output_type -> google.protobuf.Empty
	7,  // 39: remoteread.RemoteReadGateway.ListTargets:output_type -> remoteread.TargetList
	4,  // 40: remoteread.RemoteReadGateway.GetTargetStatus:output_type -> remoteread.TargetStatus
	21, // 41: remoteread.RemoteReadGateway.Start:output_type -> google.protobuf.Empty
	21, // 42: remoteread.RemoteReadGateway.Stop:output_type -> google.protobuf.Empty
	21, // 43: remoteread.RemoteReadGateway.UpdateTargetStatus:output_type -> google.protobuf.Empty
	21, // 44: remoteread.RemoteReadAgent.Start:output_type -> google.protobuf.Empty
	21, // 45: remoteread.RemoteReadAgent.Stop:output_type -> google.protobuf.Empty
	21, // 46: remoteread.RemoteReadAgent.UpdateTargetStatus:output_type -> google.protobuf.Empty
	36, // [36:47] is the sub-list for method output_type
	25, // [25:36] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_init() }
func file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_init() {
	if File_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetDiff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetEditRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetStatusUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LabelMatcher); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Progress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_goTypes,
		DependencyIndexes: file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_depIdxs,
		EnumInfos:         file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_enumTypes,
		MessageInfos:      file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_msgTypes,
	}.Build()
	File_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto = out.File
	file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_rawDesc = nil
	file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_goTypes = nil
	file_github_cim_rancher_opni_plugins_metrics_pkg_apis_remoteread_remoteread_proto_depIdxs = nil
}
