#!/bin/bash
set -ex

source $(dirname $0)/version

cd $(dirname $0)/..

go generate

mkdir -p bin
if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi
LINKFLAGS="-X github.com/rancher/opnictl.Version=$VERSION"
LINKFLAGS="-X github.com/rancher/opnictl.GitCommit=$COMMIT $LINKFLAGS"
CGO_ENABLED=0 go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/opnictl
if [ "$CROSS" = "true" ] && [ "$ARCH" = "amd64" ]; then
    GOOS=darwin go build -ldflags "$LINKFLAGS" -o bin/opnictl-darwin
    GOOS=windows go build -ldflags "$LINKFLAGS" -o bin/opnictl-windows
fi
