#!/bin/bash

set -e

cd $(dirname $0)/..

ENVTEST_ASSETS_DIR=$(pwd)/testbin

source ./hack/setup-envtest.sh

mkdir -p ${ENVTEST_ASSETS_DIR}
fetch_envtest_tools ${ENVTEST_ASSETS_DIR}
setup_envtest_env ${ENVTEST_ASSETS_DIR}
echo "** STARTING TEST ** [KUBECONFIG=${KUBECONFIG}]"
go test -v --tags=e2e,demo ./... 