#!/bin/bash

set -e

cd $(dirname $0)/..

./hack/setup-envtest.sh

reg_name='registry.local'
reg_port='5000'

# Annotate nodes with registry info for Tilt to auto-detect
echo "Annotating nodes with registry info..."
DONE=""
nodes=$(kubectl get nodes -o go-template --template='{{range .items}}{{printf "%s\n" .metadata.name}}{{end}}')
for node in $nodes; do
  kubectl annotate node "${node}" \
          tilt.dev/registry=k3dsvc:${reg_port} \
          tilt.dev/registry-from-cluster=${reg_name}:${reg_port}
done

echo "** STARTING TEST ** [KUBECONFIG=${KUBECONFIG}]"
tilt ci e2e-tests