#!/bin/bash
set -e

cd $(dirname $0)/..

./hack/setup-envtest.sh

echo "** STARTING TEST ** [KUBECONFIG=${KUBECONFIG}]"
go test ./... -race -coverprofile cover.out -v --ginkgo.label-filter "(unit || controller) && !demo"
mv cover.out dist/
