#!/bin/bash

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
elif [[ -n "$DRONE_PULL_REQUEST" ]]; then
    VERSION="dev"
elif [[ -n "$CI" ]]; then
    VERSION="latest"
else
    VERSION="dev"
fi