{{- if .Values.logging.enabled }}
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opni
  namespace: {{ include "opni.namespace" . }}
spec:
  general:
    httpPort: 9200
    vendor: opensearch
    version: {{ .Values.logging.opensearch.version }}
    serviceName: {{ include "opni.fullname" . }}-os-svc
    setVMMaxMapCount: true
    image: "{{ template "system_default_registry" . }}{{ .Values.logging.opensearch.image.repository }}:{{ .Values.logging.opensearch.version }}-{{ .Chart.AppVersion }}"
  {{- if .Values.ai.enabled }}
    additionalVolumes:
    - name: nkey
      path: /etc/nkey
      secret:
        defaultMode: 420
        secretName: opni-nats-client
    - configMap:
        name: opni-preprocessing-config
      name: pluginsettings
      path: /usr/share/opensearch/config/preprocessing
  {{- end }}
  confMgmt:
    autoScaler: false
    monitoring: false
  dashboards:
    enable: true
    version: {{ .Values.logging.dashboards.version }}
    replicas: {{ .Values.logging.dashboards.replicas }}
    image: "{{ template "system_default_registry" . }}{{ .Values.logging.dashboards.image.repository }}:{{ .Values.logging.dashboards.version }}-{{ .Chart.AppVersion }}"
    additionalConfig:
      opensearchDashboards.branding.logo.defaultUrl: "https://raw.githubusercontent.com/rancher/opni/main/branding/opni-logo-dark.svg"
      opensearchDashboards.branding.mark.defaultUrl: "https://raw.githubusercontent.com/rancher/opni/main/branding/opni-mark.svg"
      opensearchDashboards.branding.loadingLogo.defaultUrl: "https://raw.githubusercontent.com/rancher/opni/main/branding/opni-loading.svg"
      opensearchDashboards.branding.loadingLogo.darkModeUrl: "https://raw.githubusercontent.com/rancher/opni/main/branding/opni-loading-dark.svg"
      opensearchDashboards.branding.faviconUrl: "https://raw.githubusercontent.com/rancher/opni/main/branding/favicon.png"
      opensearchDashboards.branding.applicationTitle: "Opni Logging"
  nodePools:
  - component: master
    replicas: {{ .Values.logging.opensearch.controlplane.replicas }}
    diskSize: 20Gi
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        memory: 1Gi
    roles:
    - master
  {{- if .Values.logging.opensearch.persistence.enabled }}
    {{- if .Values.logging.opensearch.persistence.storageClass }}
    persistence:
      pvc:
        storageClass: {{ .Values.logging.opensearch.persistence.storageClass }}
        accessModes:
        - ReadWriteOnce
    {{- end}}
  {{- else }}
    persistence:
      emptyDir: {}
  {{- end }}
  - component: nodes
    replicas: {{ .Values.logging.opensearch.data.replicas }}
    diskSize: {{ .Values.logging.opensearch.data.diskSize }}
    {{- with .Values.logging.opensearch.data.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    jvm: {{ .Values.logging.opensearch.data.jvm }}
    roles:
    - data
  {{- if .Values.logging.opensearch.persistence.enabled }}
    {{- if .Values.logging.opensearch.persistence.storageClass }}
    persistence:
      pvc:
        storageClass: {{ .Values.logging.opensearch.persistence.storageClass }}
        accessModes:
        - ReadWriteOnce
    {{- end}}
  {{- else }}
    persistence:
      emptyDir: {}
  {{- end }}
  {{- if .Values.ai.enabled }}
  - component: ingest
    replicas: 2
    diskSize: 30Gi
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        memory: 1Gi
    roles:
    - ingest
  {{- if .Values.logging.opensearch.persistence.enabled }}
    {{- if .Values.logging.opensearch.persistence.storageClass }}
    persistence:
      pvc:
        storageClass: {{ .Values.logging.opensearch.persistence.storageClass }}
        accessModes:
        - ReadWriteOnce
    {{- end}}
  {{- else }}
    persistence:
      emptyDir: {}
  {{- end }}
  {{- end }}
{{- end }}