// Code generated by internal/codegen. DO NOT EDIT.

// Code generated by cli_gen.go DO NOT EDIT.
// source: github.com/rancher/opni/internal/cortex/config/validation/limits.proto

package validation

import (
	flagutil "github.com/rancher/opni/pkg/util/flagutil"
	pflag "github.com/spf13/pflag"
	proto "google.golang.org/protobuf/proto"
	strings "strings"
	time "time"
)

func (in *DisabledRuleGroup) DeepCopyInto(out *DisabledRuleGroup) {
	out.Reset()
	proto.Merge(out, in)
}

func (in *DisabledRuleGroup) DeepCopy() *DisabledRuleGroup {
	return proto.Clone(in).(*DisabledRuleGroup)
}

func (in *Limits) DeepCopyInto(out *Limits) {
	out.Reset()
	proto.Merge(out, in)
}

func (in *Limits) DeepCopy() *Limits {
	return proto.Clone(in).(*Limits)
}

func (in *RelabelConfig) DeepCopyInto(out *RelabelConfig) {
	out.Reset()
	proto.Merge(out, in)
}

func (in *RelabelConfig) DeepCopy() *RelabelConfig {
	return proto.Clone(in).(*RelabelConfig)
}

func (in *Limits) FlagSet(prefix ...string) *pflag.FlagSet {
	fs := pflag.NewFlagSet("Limits", pflag.ExitOnError)
	fs.SortFlags = true
	fs.Var(flagutil.FloatPtrValue(flagutil.Ptr[float64](25000), &in.IngestionRate), strings.Join(append(prefix, "ingestion-rate"), "."), "Per-user ingestion rate limit in samples per second.")
	fs.Var(flagutil.StringPtrValue(flagutil.Ptr("local"), &in.IngestionRateStrategy), strings.Join(append(prefix, "ingestion-rate-strategy"), "."), "Whether the ingestion rate limit should be applied individually to each distributor instance (local), or evenly shared across the cluster (global).")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](50000), &in.IngestionBurstSize), strings.Join(append(prefix, "ingestion-burst-size"), "."), "Per-user allowed ingestion burst size (in number of samples).")
	fs.Var(flagutil.BoolPtrValue(flagutil.Ptr(false), &in.AcceptHaSamples), strings.Join(append(prefix, "accept-ha-samples"), "."), "Flag to enable, for all users, handling of samples with external labels identifying replicas in an HA Prometheus setup.")
	fs.Var(flagutil.StringPtrValue(flagutil.Ptr("cluster"), &in.HaClusterLabel), strings.Join(append(prefix, "ha-cluster-label"), "."), "Prometheus label to look for in samples to identify a Prometheus HA cluster.")
	fs.Var(flagutil.StringPtrValue(flagutil.Ptr("__replica__"), &in.HaReplicaLabel), strings.Join(append(prefix, "ha-replica-label"), "."), "Prometheus label to look for in samples to identify a Prometheus HA replica.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.HaMaxClusters), strings.Join(append(prefix, "ha-max-clusters"), "."), "Maximum number of clusters that HA tracker will keep track of for single user. 0 to disable the limit.")
	fs.StringSliceVar(&in.DropLabels, strings.Join(append(prefix, "drop-labels"), "."), nil, "This flag can be used to specify label names that to drop during sample ingestion within the distributor and can be repeated in order to drop multiple labels.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](1024), &in.MaxLabelNameLength), strings.Join(append(prefix, "max-label-name-length"), "."), "Maximum length accepted for label names")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](2048), &in.MaxLabelValueLength), strings.Join(append(prefix, "max-label-value-length"), "."), "Maximum length accepted for label value. This setting also applies to the metric name")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](30), &in.MaxLabelNamesPerSeries), strings.Join(append(prefix, "max-label-names-per-series"), "."), "Maximum number of label names per series.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.MaxLabelsSizeBytes), strings.Join(append(prefix, "max-labels-size-bytes"), "."), "Maximum combined size in bytes of all labels and label values accepted for a series. 0 to disable the limit.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](1024), &in.MaxMetadataLength), strings.Join(append(prefix, "max-metadata-length"), "."), "Maximum length accepted for metric metadata. Metadata refers to Metric Name, HELP and UNIT.")
	fs.Var(flagutil.BoolPtrValue(flagutil.Ptr(false), &in.RejectOldSamples), strings.Join(append(prefix, "reject-old-samples"), "."), "Reject old samples.")
	fs.Var(flagutil.DurationpbValue(flagutil.Ptr[time.Duration](336*time.Hour), &in.RejectOldSamplesMaxAge), strings.Join(append(prefix, "reject-old-samples-max-age"), "."), "Maximum accepted sample age before rejecting.")
	fs.Var(flagutil.DurationpbValue(flagutil.Ptr[time.Duration](10*time.Minute), &in.CreationGracePeriod), strings.Join(append(prefix, "creation-grace-period"), "."), "Duration which table will be created/deleted before/after it's needed; we won't accept sample from before this time.")
	fs.Var(flagutil.BoolPtrValue(flagutil.Ptr(true), &in.EnforceMetadataMetricName), strings.Join(append(prefix, "enforce-metadata-metric-name"), "."), "Enforce every metadata has a metric name.")
	fs.Var(flagutil.BoolPtrValue(flagutil.Ptr(true), &in.EnforceMetricName), strings.Join(append(prefix, "enforce-metric-name"), "."), "Enforce every sample has a metric name.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.IngestionTenantShardSize), strings.Join(append(prefix, "ingestion-tenant-shard-size"), "."), "The default tenant's shard size when the shuffle-sharding strategy is used. Must be set both on ingesters and distributors. When this setting is specified in the per-tenant overrides, a value of 0 disables shuffle sharding for the tenant.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.MaxExemplars), strings.Join(append(prefix, "max-exemplars"), "."), "Enables support for exemplars in TSDB and sets the maximum number that will be stored. less than zero means disabled. If the value is set to zero, cortex will fallback to blocks-storage.tsdb.max-exemplars value.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](100000), &in.MaxSeriesPerQuery), strings.Join(append(prefix, "max-series-per-query"), "."), "The maximum number of series for which a query can fetch samples from each ingester. This limit is enforced only in the ingesters (when querying samples not flushed to the storage yet) and it's a per-instance limit. This limit is ignored when running the Cortex blocks storage. When running Cortex with blocks storage use -querier.max-fetched-series-per-query limit instead.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](5000000), &in.MaxSeriesPerUser), strings.Join(append(prefix, "max-series-per-user"), "."), "The maximum number of active series per user, per ingester. 0 to disable.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](50000), &in.MaxSeriesPerMetric), strings.Join(append(prefix, "max-series-per-metric"), "."), "The maximum number of active series per metric name, per ingester. 0 to disable.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.MaxGlobalSeriesPerUser), strings.Join(append(prefix, "max-global-series-per-user"), "."), "The maximum number of active series per user, across the cluster before replication. 0 to disable. Supported only if -distributor.shard-by-all-labels is true.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.MaxGlobalSeriesPerMetric), strings.Join(append(prefix, "max-global-series-per-metric"), "."), "The maximum number of active series per metric name, across the cluster before replication. 0 to disable.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](8000), &in.MaxMetadataPerUser), strings.Join(append(prefix, "max-metadata-per-user"), "."), "The maximum number of active metrics with metadata per user, per ingester. 0 to disable.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](10), &in.MaxMetadataPerMetric), strings.Join(append(prefix, "max-metadata-per-metric"), "."), "The maximum number of metadata per metric, per ingester. 0 to disable.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.MaxGlobalMetadataPerUser), strings.Join(append(prefix, "max-global-metadata-per-user"), "."), "The maximum number of active metrics with metadata per user, across the cluster. 0 to disable. Supported only if -distributor.shard-by-all-labels is true.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.MaxGlobalMetadataPerMetric), strings.Join(append(prefix, "max-global-metadata-per-metric"), "."), "The maximum number of metadata per metric, across the cluster. 0 to disable.")
	fs.Var(flagutil.DurationpbValue(flagutil.Ptr[time.Duration](0), &in.OutOfOrderTimeWindow), strings.Join(append(prefix, "out-of-order-time-window"), "."), "[Experimental] Configures the allowed time window for ingestion of out-of-order samples. Disabled (0s) by default.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](2000000), &in.MaxFetchedChunksPerQuery), strings.Join(append(prefix, "max-fetched-chunks-per-query"), "."), "Maximum number of chunks that can be fetched in a single query from ingesters and long-term storage. This limit is enforced in the querier, ruler and store-gateway. 0 to disable.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.MaxFetchedSeriesPerQuery), strings.Join(append(prefix, "max-fetched-series-per-query"), "."), "The maximum number of unique series for which a query can fetch samples from each ingesters and blocks storage. This limit is enforced in the querier, ruler and store-gateway. 0 to disable")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.MaxFetchedChunkBytesPerQuery), strings.Join(append(prefix, "max-fetched-chunk-bytes-per-query"), "."), "Deprecated (use max-fetched-data-bytes-per-query instead): The maximum size of all chunks in bytes that a query can fetch from each ingester and storage. This limit is enforced in the querier, ruler and store-gateway. 0 to disable.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.MaxFetchedDataBytesPerQuery), strings.Join(append(prefix, "max-fetched-data-bytes-per-query"), "."), "The maximum combined size of all data that a query can fetch from each ingester and storage. This limit is enforced in the querier and ruler for `query`, `query_range` and `series` APIs. 0 to disable.")
	fs.Var(flagutil.DurationpbValue(flagutil.Ptr[time.Duration](0), &in.MaxQueryLookback), strings.Join(append(prefix, "max-query-lookback"), "."), "Limit how long back data (series and metadata) can be queried, up until <lookback> duration ago. This limit is enforced in the query-frontend, querier and ruler. If the requested time range is outside the allowed range, the request will not fail but will be manipulated to only query data within the allowed time range. 0 to disable.")
	fs.Var(flagutil.DurationpbValue(flagutil.Ptr[time.Duration](0), &in.MaxQueryLength), strings.Join(append(prefix, "max-query-length"), "."), "Limit the query time range (end - start time). This limit is enforced in the query-frontend (on the received query) and in the querier (on the query possibly split by the query-frontend). 0 to disable.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](14), &in.MaxQueryParallelism), strings.Join(append(prefix, "max-query-parallelism"), "."), "Maximum number of split queries will be scheduled in parallel by the frontend.")
	fs.Var(flagutil.DurationpbValue(flagutil.Ptr[time.Duration](1*time.Minute), &in.MaxCacheFreshness), strings.Join(append(prefix, "max-cache-freshness"), "."), "Most recent allowed cacheable result per-tenant, to prevent caching very recent results that might still be in flux.")
	fs.Var(flagutil.FloatPtrValue(flagutil.Ptr[float64](0), &in.MaxQueriersPerTenant), strings.Join(append(prefix, "max-queriers-per-tenant"), "."), "Maximum number of queriers that can handle requests for a single tenant. If set to 0 or value higher than number of available queriers, *all* queriers will handle requests for the tenant. If the value is < 1, it will be treated as a percentage and the gets a percentage of the total queriers. Each frontend (or query-scheduler, if used) will select the same set of queriers for the same tenant (given that all queriers are connected to all frontends / query-schedulers). This option only works with queriers connecting to the query-frontend / query-scheduler, not when using downstream URL.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](100), &in.MaxOutstandingRequestsPerTenant), strings.Join(append(prefix, "max-outstanding-requests-per-tenant"), "."), "Maximum number of outstanding requests per tenant per request queue (either query frontend or query scheduler); requests beyond this error with HTTP 429.")
	fs.Var(flagutil.DurationpbValue(flagutil.Ptr[time.Duration](0), &in.RulerEvaluationDelayDuration), strings.Join(append(prefix, "ruler-evaluation-delay-duration"), "."), "Duration to delay the evaluation of rules to ensure the underlying metrics have been pushed to Cortex.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.RulerTenantShardSize), strings.Join(append(prefix, "ruler-tenant-shard-size"), "."), "The default tenant's shard size when the shuffle-sharding strategy is used by ruler. When this setting is specified in the per-tenant overrides, a value of 0 disables shuffle sharding for the tenant.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.RulerMaxRulesPerRuleGroup), strings.Join(append(prefix, "ruler-max-rules-per-rule-group"), "."), "Maximum number of rules per rule group per-tenant. 0 to disable.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.RulerMaxRuleGroupsPerTenant), strings.Join(append(prefix, "ruler-max-rule-groups-per-tenant"), "."), "Maximum number of rule groups per-tenant. 0 to disable.")
	fs.Var(flagutil.FloatPtrValue(flagutil.Ptr[float64](0), &in.StoreGatewayTenantShardSize), strings.Join(append(prefix, "store-gateway-tenant-shard-size"), "."), "The default tenant's shard size when the shuffle-sharding strategy is used. Must be set when the store-gateway sharding is enabled with the shuffle-sharding strategy. When this setting is specified in the per-tenant overrides, a value of 0 disables shuffle sharding for the tenant. If the value is < 1 the shard size will be a percentage of the total store-gateways.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.MaxDownloadedBytesPerRequest), strings.Join(append(prefix, "max-downloaded-bytes-per-request"), "."), "The maximum number of data bytes to download per gRPC request in Store Gateway, including Series/LabelNames/LabelValues requests. 0 to disable.")
	fs.Var(flagutil.DurationpbValue(flagutil.Ptr[time.Duration](0), &in.CompactorBlocksRetentionPeriod), strings.Join(append(prefix, "compactor-blocks-retention-period"), "."), "Delete blocks containing samples older than the specified retention period. 0 to disable.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.CompactorTenantShardSize), strings.Join(append(prefix, "compactor-tenant-shard-size"), "."), "The default tenant's shard size when the shuffle-sharding strategy is used by the compactor. When this setting is specified in the per-tenant overrides, a value of 0 disables shuffle sharding for the tenant.")
	fs.Var(flagutil.IPNetSliceValue(nil, &in.AlertmanagerReceiversFirewallBlockCidrNetworks), strings.Join(append(prefix, "alertmanager-receivers-firewall-block-cidr-networks"), "."), "Comma-separated list of network CIDRs to block in Alertmanager receiver integrations.")
	fs.Var(flagutil.BoolPtrValue(flagutil.Ptr(false), &in.AlertmanagerReceiversFirewallBlockPrivateAddresses), strings.Join(append(prefix, "alertmanager-receivers-firewall-block-private-addresses"), "."), "True to block private and local addresses in Alertmanager receiver integrations. It blocks private addresses defined by  RFC 1918 (IPv4 addresses) and RFC 4193 (IPv6 addresses), as well as loopback, local unicast and local multicast addresses.")
	fs.Var(flagutil.FloatPtrValue(flagutil.Ptr[float64](0), &in.AlertmanagerNotificationRateLimit), strings.Join(append(prefix, "alertmanager-notification-rate-limit"), "."), "Per-user rate limit for sending notifications from Alertmanager in notifications/sec. 0 = rate limit disabled. Negative value = no notifications are allowed.")
	fs.Var(flagutil.StringToFloat64Value(map[string]float64{}, &in.AlertmanagerNotificationRateLimitPerIntegration), strings.Join(append(prefix, "alertmanager-notification-rate-limit-per-integration"), "."), "Per-integration notification rate limits. Value is a map, where each key is integration name and value is a rate-limit (float). On command line, this map is given in JSON format. Rate limit has the same meaning as -alertmanager.notification-rate-limit, but only applies for specific integration. Allowed integration names: webhook, email, pagerduty, opsgenie, wechat, slack, victorops, pushover, sns, telegram, discord, webex, msteams.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.AlertmanagerMaxConfigSizeBytes), strings.Join(append(prefix, "alertmanager-max-config-size-bytes"), "."), "Maximum size of configuration file for Alertmanager that tenant can upload via Alertmanager API. 0 = no limit.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.AlertmanagerMaxTemplatesCount), strings.Join(append(prefix, "alertmanager-max-templates-count"), "."), "Maximum number of templates in tenant's Alertmanager configuration uploaded via Alertmanager API. 0 = no limit.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.AlertmanagerMaxTemplateSizeBytes), strings.Join(append(prefix, "alertmanager-max-template-size-bytes"), "."), "Maximum size of single template in tenant's Alertmanager configuration uploaded via Alertmanager API. 0 = no limit.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.AlertmanagerMaxDispatcherAggregationGroups), strings.Join(append(prefix, "alertmanager-max-dispatcher-aggregation-groups"), "."), "Maximum number of aggregation groups in Alertmanager's dispatcher that a tenant can have. Each active aggregation group uses single goroutine. When the limit is reached, dispatcher will not dispatch alerts that belong to additional aggregation groups, but existing groups will keep working properly. 0 = no limit.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.AlertmanagerMaxAlertsCount), strings.Join(append(prefix, "alertmanager-max-alerts-count"), "."), "Maximum number of alerts that a single user can have. Inserting more alerts will fail with a log message and metric increment. 0 = no limit.")
	fs.Var(flagutil.IntPtrValue(flagutil.Ptr[int32](0), &in.AlertmanagerMaxAlertsSizeBytes), strings.Join(append(prefix, "alertmanager-max-alerts-size-bytes"), "."), "Maximum total size of alerts that a single user can have, alert size is the sum of the bytes of its labels, annotations and generatorURL. Inserting more alerts will fail with a log message and metric increment. 0 = no limit.")
	return fs
}
