kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: training-controller-rb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: training-controller-rb
