apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-controller
  namespace: model-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-controller
  template:
    metadata:
      labels:
        app: training-controller
    spec:
      containers:
      - name: training-controller
        image: tybalex/training-controller
        imagePullPolicy: Always
        env:
        - name: NATS_SERVER_URL
          value: "nats://nats_client:VfU6TcAl9x@nats-client.default.svc:4222"
        - name: MINIO_ACCESS_KEY
          value: "myaccesskey"
        - name: MINIO_SECRET_KEY
          value: "mysecretkey"