{
 "title": "Infrastructure Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "opni_cluster_info @ end()", "legendFormat": "__auto" },
    { "expr": "opni_agent_up", "legendFormat": "__auto" },
    { "expr": "opni_agent_ready", "legendFormat": "__auto" },
    { "expr": "cluster:node_cpu:ratio", "legendFormat": "__auto" },
    {
     "expr": "sum by(__tenant_id__) (instance:node_num_cpu:sum)",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - (:node_memory_MemAvailable_bytes:sum / on(__tenant_id__) sum by(__tenant_id__) (node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(__tenant_id__) (node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - sum by(__tenant_id__) (node_filesystem_avail_bytes{job=\"node-exporter\", device=~\"^/dev.*\"}) / sum by(__tenant_id__) (node_filesystem_size_bytes{job=\"node-exporter\", device=~\"^/dev.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(__tenant_id__) (node_filesystem_size_bytes{job=\"node-exporter\", device=~\"^/dev.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Usage by Namespace",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cpus" } },
   "targets": [
    {
     "expr": "sum by(namespace, __tenant_id__) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) * on(__tenant_id__) group_left(friendly_name) group by(__tenant_id__, friendly_name) (opni_cluster_info @ end())",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage By Cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cluster:node_cpu:ratio * on(__tenant_id__) group_left(friendly_name) group by(__tenant_id__, friendly_name) (opni_cluster_info @ end())",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Network Throughput by Cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(__tenant_id__) (irate(container_network_receive_bytes_total[$__rate_interval])) * on(__tenant_id__) group_left(friendly_name) group by(__tenant_id__, friendly_name) (opni_cluster_info @ end())",
     "legendFormat": "[Rx] {{friendly_name}}"
    },
    {
     "expr": "sum by(__tenant_id__) (-irate(container_network_transmit_bytes_total[$__rate_interval])) * on(__tenant_id__) group_left(friendly_name) group by(__tenant_id__, friendly_name) (opni_cluster_info @ end())",
     "legendFormat": "[Tx] {{friendly_name}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage by Namespace",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace, __tenant_id__) (node_namespace_pod_container:container_memory_rss) * on(__tenant_id__) group_left(friendly_name) group by(__tenant_id__, friendly_name) (opni_cluster_info @ end())",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage By Cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (:node_memory_MemAvailable_bytes:sum / on(__tenant_id__) sum by(__tenant_id__) (node_memory_MemTotal_bytes)) * on(__tenant_id__) group_left(friendly_name) group by(__tenant_id__, friendly_name) (opni_cluster_info @ end())",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Kubelet Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors_total{job=\"kubelet\",}[$__rate_interval])) by (__tenant_id__, operation_type, node) * on(__tenant_id__) group_left(friendly_name) group by(__tenant_id__, friendly_name) (opni_cluster_info @ end())",
     "legendFormat": "{{friendly_name}} / {{node}}"
    }
   ]
  },
  {
   "title": "Historical Agent Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "group by(__tenant_id__, summary) (opni_agent_status_summary) * on(__tenant_id__)  group_left(friendly_name) group by(__tenant_id__, friendly_name) (opni_cluster_info @ end())",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IOPS By Cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (__tenant_id__) (rate(node_disk_read_bytes_total[$__rate_interval])+rate(node_disk_written_bytes_total[$__rate_interval])) * on(__tenant_id__) group_left(friendly_name) group by(__tenant_id__, friendly_name) (opni_cluster_info @ end())",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Blocks in Long Term Storage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "label_replace(sum by(user) (cortex_bucket_blocks_count), \"__tenant_id__\", \"$1\", \"user\", \"(.*)\")  * on(__tenant_id__) group_left(friendly_name) group by(__tenant_id__, friendly_name) (opni_cluster_info @ end())",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}